heigth = models.IntegerField(max_length=20, null=True, blank=True)
width = models.CharField(max_length=200)
length = models.DecimalField(max_digits=10, decimal_places=2)
crating = models.IntegerField(max_length=20, null=True, blank=True)
rating = models.IntegerField(max_length=20, null=True, blank=True)
capacity = models.CharField(max_length=30, null=True, blank=True)
cells = models.CharField(max_length=30, null=True, blank=True)
price = models.CharField(max_length=20, null=True, blank=True)
weight = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
description = models.CharField(max_length=3000)
