# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('page', models.CharField(max_length=1000)),
                ('heigth', models.FloatField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('crating', models.FloatField(blank=True, null=True)),
                ('cchargerating', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('capacity', models.FloatField()),
                ('cells', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=30, null=True)),
                ('bigimg', models.CharField(blank=True, max_length=30, null=True)),
                ('page', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maxCurrent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resistance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maxThrust', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maxVoltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
